Switch to core22 base
canonical/docker-snap pull request #93
Opened 2023-03-13 20:13 UTC by jocado

Make required changes to enable snap build with core22 base

Relates to: https://github.com/docker-snap/docker-snap/issues/65

2023-03-13 20:17 UTC, xnox approved these changes
But let's see how our ci will react to things.

2023-03-13 20:34 UTC, jocado commented
I've pushed a change to try and fix the previous workflow failure, but it seems you have to approve each run @xnox

2023-03-13 20:36 UTC, jocado commented
I guess its because the branch is in my own fork

2023-03-13 21:14 UTC, jocado commented
Snap was built at least.

I'm not 100% how to interpret the failure: https://github.com/docker-snap/docker-snap/actions/runs/4409275831/jobs/7725502411#step:10:6

Do you have any thoughts @xnox ?

Worth noting that the snap I built locally ran fine on a UC22 host, tested with hello-world docker image.

I suppose if this was my own CI permission in, I would add some debug to the workflow and run it again.

2023-03-13 21:31 UTC, tianon commented
A core22 snap is not supported on an Ubuntu 20.04 system, right?  If it is, then this failure is worth digging more into, but if it isn't then you probably just want to update this line to `ubuntu-22.04` instead:

https://github.com/docker-snap/docker-snap/blob/975f02462d78b74b96da4629dff480d14ec57542/.github/workflows/smoke-test.yml#L14

2023-03-13 21:35 UTC, xnox commented
> A core22 snap is not supported on an Ubuntu 20.04 system, right?  If it is, then this failure is worth digging more into, but if it isn't then you probably just want to update this line to `ubuntu-22.04` instead:
> 
> https://github.com/docker-snap/docker-snap/blob/975f02462d78b74b96da4629dff480d14ec57542/.github/workflows/smoke-test.yml#L14

We could update to 22.04 host base for workflows. But in theory it should work. We have Lxd snap built on any base, and running on any host. Including when Lxd snap was base:core20 and when it moved to base:core22.

2023-03-13 21:46 UTC, tianon commented
Ah, so the failure probably _is_ worth investigating then, because that's even the most basic use case of `docker run hello-world` failing :sweat_smile:

2023-03-13 22:04 UTC, xnox commented
> Ah, so the failure probably _is_ worth investigating then, because that's even the most basic use case of `docker run hello-world` failing sweat_smile

i think it might be fun things between focal host, core22 confinement, and changes in apparmor_parser --version which tries to parse things, and gets a denial to access /abi/ subdir, that is there, but not allowed to by the docker snapd interface.

This probably works on UC because we don't ship /abi/ directory on UC and nothing tries to access it either. Fun things.

Somewhat wonder if we should try upgrade to core20 first, cause fixing this issue may require upgrades to docker itself, and/or changes to the snapd interfaces.

2023-03-13 22:09 UTC, xnox requested changes
Block merging until we get feedback from interface maintainers and apparmor maintainers.

2023-03-14 18:24 UTC, merged

2023-03-14 18:55 UTC, jocado commented
@xnox Just to join the dots - what was the feedback from interface maintainers and apparmor maintainers ?